insta_scrape/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using insta_scrape.Classes;
using insta_scrape.Authentication;

namespace insta_scrape.Controllers
{
    public class HomeController : Controller
    {
        private DBController DB = new DBController();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";            
            return View();
        }

        [Authorize]
        public void Logout()
        {
            FormsAuthentication.SignOut();
            FormsAuthentication.RedirectToLoginPage();
        }

        [Authorize]
        public ActionResult User_Profile()
        {
            ViewBag.Message = "User Profile";
            var userSearches = DB.GetList<UserSearches>(x => x.User.Equals(HttpContext.User.Identity.Name)).ToList();
            ViewBag.MyLinks = userSearches;
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult User_Profile(string new_password, string confirm_password)
        {
            ViewBag.Message = "User Profile";
            var userSearches = DB.GetList<UserSearches>(x => x.User.Equals(HttpContext.User.Identity.Name)).ToList();
            ViewBag.MyLinks = userSearches;
            if(new_password == confirm_password)
            {
                var user = DB.Get<Logins>(x => x.username.Equals(HttpContext.User.Identity.Name));
                user.password = PasswordHelper.GetHash(new_password);
                DB.Update(user);
            }
            return View();
        }


        public ActionResult Login()
        {

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(Logins model)
        {
            try
            {
                var user = DB.Get<Logins>(x => x.username.Equals(model.username));
                if (user != null)
                {
                    if (user.banned == true)
                    {
                        ViewBag.Error = "User blocked";
                        return View();
                    }
                    if (user.password.Equals(PasswordHelper.GetHash(model.password)))
                    {
                        FormsAuthentication.RedirectFromLoginPage(model.username, true);
                    }
                    else
                    {
                        ViewBag.Error = "Incorrect password";
                        return View();
                    }
                }
                else
                {
                    ViewBag.Error = "User not found";
                    return View();
                }
                return null;
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message + "\n" + ex.InnerException;
                return View();
            }
        }

        [AllowAnonymous]
        public ActionResult Register(){

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Register(Register model)
        {
            try
            {
                var user = DB.Get<Logins>(x => x.username.Equals(model.username));
                if (user == null)
                {
                    if (model.password == model.confirm_password)
                    {
                        var login = new Logins { username = model.username, password = PasswordHelper.GetHash(model.password) };
                        DB.Save(login);
                        ViewBag.Success = "Registration succesful!";
                        return View("Login");
                    }
                    else
                    {
                        ViewBag.Error = "Passwords do not match!";
                        return View();
                    }

                }
                else
                {
                    ViewBag.Error = "Username already taken!";
                    return View();
                }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message + "\n" + ex.InnerException;
                return View();
            }
            
        }

    }
}

insta_scrape/Controllers/ScrapeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.IO;
using System.Globalization;
using insta_scrape.Classes;
using insta_scrape.Models;
using System.Text;
namespace insta_scrape.Controllers
{
    public class ScrapeController : Controller
    {
        private DBController DB = new DBController();
        [Authorize]
        public ActionResult Scrape()
        {
            return View();
        }
        [Authorize]
        public ActionResult Main_Scrape()
        {
            ViewBag.Title = "Scraped data";
            return View();
        }
        [HttpPost]
        [Authorize]
        public ActionResult Main_Scrape(Search_Details sDetails)
        {
            if (!string.IsNullOrEmpty(sDetails.search_term))
            {
                var actualResult = DB.GetList<Searches>(x => x.Search.Equals(sDetails.search_term)).ToList();
                var scrapeResult = new Searches();
                var stras = sDetails.search_store.ToString();
                if(actualResult.FirstOrDefault<Searches>(x => x.Store.Contains(stras.ToString())) != null){
                    scrapeResult = actualResult.First<Searches>(x => x.Store.Contains(stras.ToString()));
                }
                
                //vartotoju paieskos kaupiamos DB pagal vartotojo vardą, laiką, paieškos kriterijų
                UserSearches userSearch = new UserSearches { Data = DateTime.Now, SearchTerm = sDetails.search_term, User = HttpContext.User.Identity.Name };
                DB.Save(userSearch);

                TimeSpan tarpas = new TimeSpan();

                if (scrapeResult != null)
                {
                    tarpas = (DateTime.Now - scrapeResult.Data);
                }
                if (scrapeResult == null || (tarpas == TimeSpan.Zero || tarpas.Hours >= 2))
                {
                    //full pythono consolės outputas
                    string scrapeData = RunScrape(sDetails);
                    //jį sukapojam į dalis, kad gyvent lengviau būtų
                    var data = new List<FSpecs> { };
                    if (stras == "Topocentras")
                        data = RipStringApart(scrapeData, sDetails);
                    else if (stras == "Avitela")
                        data = RipStringApartAvitela(scrapeData, sDetails);
                    ViewBag.Specs = data;

                }
                else
                {
                    List<FSpecs> specsReturn = new List<FSpecs> { };
                    var searchData = DB.GetList<Searches>(x => x.Search.Equals(sDetails.search_term));
                    var test = searchData.SingleOrDefault<Searches>(x => x.Store.Equals(sDetails.search_store.ToString()));
                    var data = DB.GetList<Phone>(x => x.SearchId.Equals(test.Id)).ToList();
                    foreach (var ph in data)
                    {
                        List<string> linkai = ph.ImageLinks.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries).ToList();
                        List<string> Linkai1 = linkai.Select(x => x.Replace("https://picfit.topocentras.lt/cdn-cgi/image/fit=contain,format=auto,height=60,width=60,quality=80/", "")).ToList();
                        Linkai1 = Linkai1.Select(x => x.Replace("media/catalog/", "https://www.topocentras.lt/media/catalog/")).ToList();
                        FSpecs temp = new FSpecs { };
                        temp.links = Linkai1;
                        temp.phone = ph;
                        specsReturn.Add(temp);
                    }
                    ViewBag.Specs = specsReturn;

                }
            }
            return View("Main_Scrape", sDetails);
        }
        [HttpGet]
        [Authorize]
        public ActionResult Main_Scrape(string search_term, string sortOrder, string store)
        {

            List<FSpecs> specsReturn = new List<FSpecs> { };
            Search_Details sDetails = new Search_Details { search_term = search_term};
            if (!string.IsNullOrEmpty(search_term))
            {
                //gaunam visą console outputą vienam stringe
                var actualResult = DB.GetList<Searches>(x => x.Search.Equals(sDetails.search_term)).ToList();
                var scrapeResult = new Searches();


                if (actualResult.FirstOrDefault<Searches>(x => x.Store.Contains(store.ToString())) != null)
                {
                    scrapeResult = actualResult.First<Searches>(x => x.Store.Contains(store));
                }

                UserSearches userSearch = new UserSearches { Data = DateTime.Now, SearchTerm = search_term, User = HttpContext.User.Identity.Name };
                DB.Save(userSearch);

                TimeSpan tarpas = new TimeSpan();

                if (scrapeResult != null)
                {
                    tarpas = (DateTime.Now - scrapeResult.Data);
                }
                if (scrapeResult == null || (tarpas == TimeSpan.Zero || tarpas.Hours >= 2))
                {
                    //full pythono consolės outputas
                    string scrapeData = RunScrape(sDetails);
                    //jį sukapojam į dalis, kad gyvent lengviau būtų
                    var data = new List<FSpecs> { };
                    if (store == "Topocentras")
                        data = RipStringApart(scrapeData, sDetails);
                    else if (store == "Avitela")
                        data = RipStringApartAvitela(scrapeData, sDetails);
                    ViewBag.Specs = data;

                }
                else
                {
                    //List<FSpecs> specsReturn = new List<FSpecs> { };

                    var searchData = DB.GetList<Searches>(x => x.Search.Equals(sDetails.search_term));
                    var test = searchData.SingleOrDefault<Searches>(x => x.Store.Equals(store));
                    var data = DB.GetList<Phone>(x => x.SearchId.Equals(test.Id)).ToList();

                    foreach (var ph in data)
                    {
                        List<string> linkai = ph.ImageLinks.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries).ToList();
                        List<string> Linkai1 = linkai.Select(x => x.Replace("https://picfit.topocentras.lt/cdn-cgi/image/fit=contain,format=auto,height=60,width=60,quality=80/", "")).ToList();
                        Linkai1 = Linkai1.Select(x => x.Replace("media/catalog/", "https://www.topocentras.lt/media/catalog/")).ToList();
                        FSpecs temp = new FSpecs { };
                        temp.links = Linkai1;
                        temp.phone = ph;
                        specsReturn.Add(temp);
                    }
                    ViewBag.Specs = specsReturn;
                }
                if (sortOrder.Contains("Descending"))
                {
                    var test = specsReturn.OrderByDescending(x => x.phone.CurrentPrice).ToList();
                    ViewBag.Specs = test;
                }
                else if(sortOrder.Contains("Ascending"))
                {
                    var test = specsReturn.OrderBy(x => x.phone.CurrentPrice).ToList();
                    ViewBag.Specs = test;
                }
            }
            return View("Main_Scrape", sDetails);
        }

        //visa paimta informacija iš div'o suskaldoma į mažesnius pagal tam tikras klases TOPOCENTRO
        private List<FSpecs> RipStringApart(string data, Search_Details sData)
        {
            List<string> skirtTelefonai = data.Split(new string[] { "EndOfQuery" }, StringSplitOptions.None).ToList();
            skirtTelefonai.RemoveAt(skirtTelefonai.Count - 1);
            List<FSpecs> specsReturn = new List<FSpecs> { };
            var searchUpdates = DB.GetList<Searches>(x => x.Search.Equals(sData.search_term));
            var searchUpdate = searchUpdates.SingleOrDefault(x => x.Store.Equals(sData.search_store.ToString()));
            foreach (string sTelef in skirtTelefonai)
            {
                FSpecs temp = new FSpecs { };
                int pFrom = sTelef.IndexOf("Query: ") + "Query: ".Length;
                int pTo = sTelef.LastIndexOf("Query close");
                string difQueries = sTelef.Substring(pFrom, pTo - pFrom);

                int priceFrom = sTelef.IndexOf("ItemPrice") + "ItemPrice".Length;
                int priceTo = sTelef.LastIndexOf("EndOfItemPrice");
                string PriceQueries = sTelef.Substring(priceFrom, priceTo - priceFrom);
                List<string> Kainos = PriceQueries.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries).ToList();

                int linkFrom = sTelef.IndexOf("LinkToItem") + "LinkToItem".Length;
                int linkTo = sTelef.LastIndexOf("EndOfLinkToItem");
                string linkToItem = sTelef.Substring(linkFrom, linkTo - linkFrom).Replace("\r\n", "");

                int sFrom = sTelef.IndexOf("Info Start") + "Info Start".Length;
                int sTo = sTelef.LastIndexOf("Info Close");
                string specsd = sTelef.Substring(sFrom, sTo - sFrom);
                List<string> specsai = specsd.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries).ToList();
                specsai.AddRange(Kainos);
                Phone specs = ConvToClass(specsai.ToList());
                
                int lFrom = sTelef.IndexOf("links: ") + "links: ".Length;
                int lTo = sTelef.LastIndexOf("links close");
                string links = sTelef.Substring(lFrom, lTo - lFrom);

                List<string> linkai = links.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries).ToList();
                List<string> Linkai1 = linkai.Select(x => x.Replace("https://picfit.topocentras.lt/cdn-cgi/image/fit=contain,format=auto,height=60,width=60,quality=80/", "")).ToList();

insta_scrape/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

insta_scrape/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

insta_scrape/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br />
<br />
<!--Prisijungimo forma-->
<div class="d-flex justify-content-center align-items-center login-container">
    <!--Prisijungimo formos pradžia -->
    <div class="col-sm-6 d-flex justify-content-center align-items-center">
        @Html.ActionLink("Login", "Login", "Home", new { @class = "btn mt-5 rounded-pill btn-lg btn-custom1 btn-block text-uppercase" })
    </div>
    <div class="col-sm-6 d-flex justify-content-center align-items-center">
        @Html.ActionLink("Register", "Register", "Home", new { @class = "btn mt-5 rounded-pill btn-lg btn-custom1 btn-block text-uppercase" })
    </div>
</div>

insta_scrape/Views/Home/Login.cshtml
@using insta_scrape.Classes
@model Logins
@{
    ViewBag.Title = "Loginas";

}
<br />
<br />
<br />
<br />
<!--Prisijungimo forma-->
@if (!string.IsNullOrEmpty(ViewBag.Success))
{
    @Html.Partial("Success", (string)ViewBag.Success)
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    @Html.Partial("Error", (string)ViewBag.Error)
}

<div class="d-flex justify-content-center align-items-center login-container">
    <!--Prisijungimo formos pradžia -->
    @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "form-signin text-center" }))
    {
        <h1 class="mb-5 font-weight-light text-uppercase d-flex justify-content-center align-items-center">Login</h1>
        <br />
        <!--Vartotojo vardo laukas -->
        <!--Jeigu laukas paliktas tuščias prisijungti neleidžiama ir liepiama įvesti vartotojo vardą -->
        <div class="form-group">
            @Html.TextBoxFor(x => x.username, new { @type = "text", @id = "Login", @class = "form-control rounded-pill form-control-lg", @placeholder = "Username", @required = "", @autofocus = "" })
            <!--Klaida jeigu vartotojo vardas netinkamas -->
            <span class="help-block"></span>
        </div>

        <!--Slaptažodžio laukas -->
        <!--Jeigu laukas paliktas tuščias prisijungti neleidžiama ir liepiama įvesti slaptažodį -->
        <div class="form-group">
            @Html.TextBoxFor(x => x.password, new { @type = "password", @id = "inputPassword", @class = "form-control rounded-pill form-control-lg", @placeholder = "Password", @required = "" })
            <!--Klaida jeigu slaptažodis netinkamas -->
            <span class="help-block"></span>
        </div>


        <!--<div class="forgot-link form-group d-flex justify-content-between align-items-center">-->
        <!--Prisiminti slaptažodį funkcija-->
        <!--<div class="form-check">
            <input type="checkbox" class="form-check-input" id="remember">
            <label class="form-check-label" for="remember">Prisiminti slaptažodį</label>
        </div>-->
        <!--Pamiršto slaptažodžio atstatymas-->
        <!--<a href="atstatymas.php">Pamiršote slaptažodį?</a>-->
        <!--</div>-->
        <br />
        <button type="submit" id="btn" value="Login" class="btn mt-5 rounded-pill btn-lg btn-custom btn-block text-uppercase">Login</button>
        <p class="mt-3 font-weight-normal">Neturite paskyros? @Html.ActionLink("Register", "Register", "Home")</p>
    }
</div>

insta_scrape/Views/Home/Logout555.cshtml
@{
    ViewBag.Title = "Logout";
}

insta_scrape/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using insta_scrape.Classes
@model Register
<br />
<br />
<br />
<br />
@if (!string.IsNullOrEmpty(ViewBag.Success))
{
    @Html.Partial("Success", (string)ViewBag.Success)
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    @Html.Partial("Error", (string)ViewBag.Error)
}

<!--Register form-->
<div class="d-flex justify-content-center align-items-center login-container">
    <!--Registracijos formos pradžia -->
    <form method="post">
        <h1 class="mb-5 font-weight-light text-uppercase d-flex justify-content-center align-items-center">Register</h1>
        <br />
        <!--Email laukelis-->
        <div class="form-group">
            <input type="text" name="email" class="form-control rounded-pill form-control-lg" placeholder="E-mail">
            <!--Klaida jeigu email formatas netinkamas -->
            <span class="help-block"></span>
        </div>
        <!--Vartotojo vardo laukas -->
        <!--Jeigu laukas paliktas tuščias prisijungti neleidžiama ir liepiama įvesti vartotojo vardą -->
        <div class="form-group">
            <input type="text" name="username" class="form-control rounded-pill form-control-lg" placeholder="Username">
            <!--Klaida jeigu vartotojo vardas netinkamas -->
            <span class="help-block"></span>
        </div>

        <!--Elektroninio pašto laukas -->
        <!--Jeigu laukas paliktas tuščias prisijungti neleidžiama ir liepiama įvesti slaptažodį -->
        <!--<div class="form-group">
        <input type="text" class="form-control rounded-pill form-control-lg" placeholder="Elektroninis paštas">
    </div>-->
        <!--Slaptažodžio laukas -->
        <!--Jeigu laukas paliktas tuščias prisijungti neleidžiama ir liepiama įvesti slaptažodį -->
        <div class="form-group">
            <input type="password" name="password" class="form-control rounded-pill form-control-lg" placeholder="Password">
            <!--Klaida jeigu slaptažodis netinkamas -->
            <span class="help-block"></span>
        </div>

        <!--Slaptažodžio patvirtinimo laukas -->
        <!--Jeigu laukas paliktas tuščias prisijungti neleidžiama ir liepiama įvesti slaptažodį -->
        <div class="form-group">
            <input type="password" name="confirm_password" class="form-control rounded-pill form-control-lg" placeholder="Repeat Password">
            <!--Klaida jeigu slaptažodis nesutampa -->

        </div>
        <br />
        <button type="submit" class="btn mt-5 rounded-pill btn-lg btn-custom btn-block text-uppercase" value="Submit">Register</button>
        <p class="mt-3 font-weight-normal">Already registered? @Html.ActionLink("Login", "Login", "Home")</p>
    </form>
</div>

insta_scrape/Views/Home/Scrape.cshtml
@model Links 
<p>Stuff everywhere</p>
    @foreach (var item in links)
    {
        <img src="@item.Image" alt="Profile Image" width="200" height="200">
    }

@Html.ActionLink("Log the fuck out", "Logout", "Home")

insta_scrape/Views/Home/User_Profile.cshtml
@{
    ViewBag.Title = "Profile";
}
@using insta_scrape.Models
@Scripts.Render("~/bundles/SCRAPE")
@model ProfileLinks
<br />
<h2>@ViewBag.Message</h2>
<br />
<div class="tab">
    <button class="tablinks" onclick="openCity(event, 'Scrape_history')">Scrape history</button>
    <button class="tablinks" onclick="openCity(event, 'Change_password')">Change password</button>
    <div id="Scrape_history" class="tabcontent">
        <br />
        <h3>This is your scrape history</h3>
        @foreach (var x in ViewBag.MyLinks)
        {
            <div class="row">
                <div class="col-sm-5">@x.SearchTerm</div><div class="col-sm-6">@x.Data</div>
            </div>
        }

    </div>
    <div id="Change_password" class="tabcontent">
        <!-- Slaptažodžio keitimo forma -->
        <form method="post" class="login-form text-center">
            <h3 class="mb-5 font-weight-light text-uppercase">Slaptažodžio keitimas</h3>

            <div class="form-group">
                <input type="password" name="new_password" class="form-control rounded-pill form-control-lg" placeholder="Naujas slaptažodis">
                <!--Klaida jeigu slaptažodis netinkamas -->
                <span class="help-block"></span>
            </div>
            <div class="form-group">
                <input type="password" name="confirm_password" class="form-control rounded-pill form-control-lg" placeholder="Patvirtinkite slaptažodį">
                <!--Klaida jeigu slaptažodis netinkamas -->
                <span class="help-block"></span>
            </div>
            <!-- Keitimo patvirtinimas -->
            <div class="form-group">
                <input type="submit" class="form-control btn mt-5 rounded-pill btn-lg btn-custom1 btn-block text-uppercase" value="Change password">
            </div>
        </form>
    </div>
</div>
<br />
<br />
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-4">
        @Html.ActionLink("Logout", "Logout", "Home", new { @class = "btn mt-5 rounded-pill btn-lg btn-custom btn-block text-uppercase" })
    </div>
    <div class="col-sm-4">
        @Html.ActionLink("To the scraping", "Scrape", "Scrape", null, new { @class = "btn mt-5 rounded-pill btn-lg btn-custom btn-block text-uppercase" })
    </div>
    <div class="col-sm-2"></div>
</div>